name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up

      # - name: Run tests
      #   run: docker container exec app npm test

  DAST-owasp-zap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: '16'
      
      - name: Install OWASP ZAP
        run: |
          wget -q -O - https://raw.githubusercontent.com/zaproxy/zap-admin/master/ZapVersions.xml | grep -oP "https.*?linux\.tar\.gz" | head -n1 | xargs wget -q -O zap.tar.gz
          tar -xvf zap.tar.gz
          rm zap.tar.gz
          mv ZAP* zap
      
      - name: Run OWASP ZAP scan
        run: |
          export ZAP_PATH=$(pwd)/zap/zap.sh
          export TARGET_URL=http://localhost:3000
          $(echo $ZAP_PATH) -cmd -quickurl $TARGET_URL -quickprogress -quickscan spider
          $(echo $ZAP_PATH) -cmd -quickurl $TARGET_URL -quickprogress -quickscan activeScan

  SAST-snyk:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      
      - name: Install and configure SNYK
        run: |
          npm install -g snyk
          snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run SAST scan for lib vulnerabilities
        run: snyk test .

  SAST-njsscan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests_html njsscan
      
      - name: Run NJSScan
        run: njsscan .
        
  deploy-:
    needs: [build, SAST-snyk]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: c4st4nha/projetosrc
        tag: latest
        registry: docker.io
