name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  snyk:
   runs-on: ubuntu-latest

   steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install

      - name: Install and configure SNYK
        run: sudo npm install -g snyk && snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: snyk scan for lib vulnerabilities (SAST)
        run: sudo snyk test .
        
  sast-njsscan:
    runs-on: ubuntu-latest

    steps:    
      - uses: actions/checkout@v2
    
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'    

      - name: njsscan (install dependencies)
        run: |
          python -m pip install --upgrade pip
          pip install requests_html njsscan
          
      - name: Execute njsscan
        run: njsscan .
